import { ArrowUpRight, CalendarDays, Clock3, Sparkles } from 'lucide-react';
import PageShell from '@/components/layout/PageShell';
import { Label, Section } from '@/components/ui/primitives';
import { Reveal } from '@/components/ui/ScrollMotion';
import { useCollection } from '@/lib/siteContent';
import { safeHref, usePageContent } from '@/lib/pageContent';
const defaultPosts=[{date:'12.09.25',tag:'Creator economy',title:'Why the best creator ads do not feel like ads',color:'bg-yellow text-dark'},{date:'04.09.25',tag:'Performance',title:'The performance creative loop, explained',color:'bg-blue text-white'},{date:'28.08.25',tag:'Growth',title:'From scroll-stopping hook to scalable system',color:'blog-soft-card text-dark'},{date:'19.08.25',tag:'CRO',title:'The page is part of the ad',color:'bg-yellow text-dark'},{date:'11.08.25',tag:'Strategy',title:'What to do when everything is working a little',color:'bg-blue text-white'},{date:'02.08.25',tag:'Creators',title:'Briefing for a voice, not a demographic',color:'blog-soft-card text-dark'}];
// Chip icons stay fixed; their text is dispatchPerk1..3 in the page content.
const PERK_ICONS=[CalendarDays,Clock3,Sparkles];
const blogStyles:Record<string,string>={yellow:'bg-yellow text-dark',blue:'bg-blue text-white',soft:'blog-soft-card text-dark'};
export default function Blog(){const c=usePageContent('blog');const dispatchPerks=PERK_ICONS.map((icon,i)=>({icon,text:c[`dispatchPerk${i+1}`]})).filter(p=>p.text);const posts=useCollection('blog',defaultPosts,item=>({date:item.date,tag:item.tag,title:item.title,color:blogStyles[item.style]??blogStyles.yellow}));return <PageShell grid eyebrow={c.heroEyebrow} title={<>{c.heroTitle}<br/><span className="text-yellow">{c.heroHighlight}</span></>} intro={c.heroIntro}><Section><div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3">{posts.map((post,i)=><Reveal key={`${post.title}-${i}`} delay={(i%3)*120}><article className={`blog-card group h-full min-h-[280px] rounded-xl p-6 ${post.color}`}><div className="flex justify-between"><p className="font-mono text-xs opacity-65">{post.date}</p><ArrowUpRight size={18} className="blog-card-arrow"/></div><div className="mt-20"><p className="text-[10px] font-semibold uppercase tracking-[.14em] opacity-65">{post.tag}</p><h2 className="mt-3 font-['Urbanist',sans-serif] text-3xl font-bold leading-[1.05] tracking-[-.03em]">{post.title}</h2></div></article></Reveal>)}</div></Section><section className="dispatch-band mb-16 bg-blue text-white md:mb-24"><div className="dispatch-glow dispatch-glow-a" aria-hidden="true"/><div className="dispatch-glow dispatch-glow-b" aria-hidden="true"/><div className="container relative flex flex-col gap-8 py-12 md:flex-row md:items-stretch md:justify-between md:py-16"><Reveal className="max-w-2xl"><Label style={{color:'#FFDE59'}}>{c.dispatchLabel}</Label><h2 className="display text-5xl font-bold md:text-7xl">{c.dispatchTitle}</h2>{c.dispatchIntro&&<p className="mt-4 max-w-xl text-base leading-relaxed text-white/75 md:text-lg">{c.dispatchIntro}</p>}<ul className="mt-6 flex flex-wrap gap-3">{dispatchPerks.map(({icon:Icon,text},i)=><li key={i} className="dispatch-chip"><Icon size={14} aria-hidden="true"/>{text}</li>)}</ul></Reveal><div className="flex flex-col items-start gap-6 md:items-end md:justify-between">{posts[0]&&<div className="dispatch-latest"><p className="dispatch-latest-label"><span className="dispatch-live-dot" aria-hidden="true"/>{c.dispatchLatest}</p><p className="mt-3 font-['Urbanist',sans-serif] text-xl font-bold leading-tight tracking-[-.02em]">{posts[0].title}</p><p className="mt-3 font-mono text-xs text-white/60">{posts[0].date} · {posts[0].tag}</p></div>}<a href={safeHref(c.dispatchUrl||'/contact')} className="dispatch-btn inline-flex items-center gap-3 rounded-xl bg-yellow px-6 py-4 text-sm font-semibold uppercase tracking-[.1em] text-dark">{c.dispatchButton} <ArrowUpRight size={16} className="dispatch-btn-arrow"/></a></div></div></section></PageShell>}
